/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Product;

/**
 *
 * @author Uttam Bagora
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
 
    
    /**
     *
     * @param product
     */
    Product product;
    
    public CreateJPanel(Product product){
        initComponents();
        this.product =product;
        
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreate = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblgeographicdata = new javax.swing.JLabel();
        lbldob = new javax.swing.JLabel();
        lbltelephonenumber = new javax.swing.JLabel();
        lblfaxnumber = new javax.swing.JLabel();
        lblemailaddresses = new javax.swing.JLabel();
        lblssn = new javax.swing.JLabel();
        lblmediarecordnumber = new javax.swing.JLabel();
        lblhealthplanbeneficiarynumber = new javax.swing.JLabel();
        lblbankaccountnumber = new javax.swing.JLabel();
        lblcertificatelicensenumber = new javax.swing.JLabel();
        lblvehicleidentifiers = new javax.swing.JLabel();
        lbldeviceidentifiers = new javax.swing.JLabel();
        lbllinkedin = new javax.swing.JLabel();
        lblip = new javax.swing.JLabel();
        lblbiometricidentifiers = new javax.swing.JLabel();
        lblfullfacephoto = new javax.swing.JLabel();
        lbluniqueidentifyingnumber = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtgeographicdata = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        txttelephonenumber = new javax.swing.JTextField();
        txtfaxnumber = new javax.swing.JTextField();
        txtemailaddresses = new javax.swing.JTextField();
        txtssn = new javax.swing.JTextField();
        txtmediarecordnumber = new javax.swing.JTextField();
        txthealthplanbeneficiarynumber = new javax.swing.JTextField();
        txtbankaccountnumber = new javax.swing.JTextField();
        txtcertificatelicensenumber = new javax.swing.JTextField();
        txtvehicleidentifier = new javax.swing.JTextField();
        txtdeviceidentifiers = new javax.swing.JTextField();
        txtlinkedin = new javax.swing.JTextField();
        txtip = new javax.swing.JTextField();
        txtbiometricidentifiers = new javax.swing.JTextField();
        txtfullfacephoto = new javax.swing.JTextField();
        txtuniqueidentificationnumber = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        lblCreate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCreate.setText("Create");

        lblname.setText("                                              Name");

        lblgeographicdata.setText("                           Geographic Data");

        lbldob.setText("                                       Date of Birth");

        lbltelephonenumber.setText("                          Telephone Number");

        lblfaxnumber.setText("                                       Fax Number");

        lblemailaddresses.setText("                                Email Addresses");

        lblssn.setText("                      Social Security Number");

        lblmediarecordnumber.setText("                       Media Record Number");

        lblhealthplanbeneficiarynumber.setText("        Health plan beneficiary number");

        lblbankaccountnumber.setText("                     Bank account numbers");

        lblcertificatelicensenumber.setText("                 Certificate/license number");

        lblvehicleidentifiers.setText("Vehicle identifiers and serial numbers ");

        lbldeviceidentifiers.setText("Device identifiers and serial numbers");

        lbllinkedin.setText("                                             LinkedIn");

        lblip.setText("             Internet protocol addresses");

        lblbiometricidentifiers.setText("                           Biometric identifiers");

        lblfullfacephoto.setText("                                 Full face photos");

        lbluniqueidentifyingnumber.setText("          unique identifying number");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtgeographicdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgeographicdataActionPerformed(evt);
            }
        });

        txtdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdobActionPerformed(evt);
            }
        });

        txttelephonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelephonenumberActionPerformed(evt);
            }
        });

        txtfaxnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfaxnumberActionPerformed(evt);
            }
        });

        txtemailaddresses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailaddressesActionPerformed(evt);
            }
        });

        txtssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtssnActionPerformed(evt);
            }
        });

        txtmediarecordnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmediarecordnumberActionPerformed(evt);
            }
        });

        txthealthplanbeneficiarynumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthealthplanbeneficiarynumberActionPerformed(evt);
            }
        });

        txtbankaccountnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbankaccountnumberActionPerformed(evt);
            }
        });

        txtcertificatelicensenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcertificatelicensenumberActionPerformed(evt);
            }
        });

        txtvehicleidentifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvehicleidentifierActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbltelephonenumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblgeographicdata, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lbldob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblfaxnumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblemailaddresses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblssn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblmediarecordnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblhealthplanbeneficiarynumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblbankaccountnumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblcertificatelicensenumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbllinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtcertificatelicensenumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                .addComponent(txtbankaccountnumber, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txthealthplanbeneficiarynumber, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtmediarecordnumber, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtssn, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtemailaddresses, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtfaxnumber, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txttelephonenumber, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtdob, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtgeographicdata, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(txtlinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblip, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblbiometricidentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblfullfacephoto, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbluniqueidentifyingnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfullfacephoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtbiometricidentifiers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtip, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtuniqueidentificationnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblvehicleidentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbldeviceidentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtvehicleidentifier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdeviceidentifiers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtName, txtbankaccountnumber, txtbiometricidentifiers, txtcertificatelicensenumber, txtdeviceidentifiers, txtdob, txtemailaddresses, txtfaxnumber, txtfullfacephoto, txtgeographicdata, txthealthplanbeneficiarynumber, txtip, txtlinkedin, txtmediarecordnumber, txtssn, txttelephonenumber, txtuniqueidentificationnumber, txtvehicleidentifier});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblbankaccountnumber, lblbiometricidentifiers, lblcertificatelicensenumber, lbldeviceidentifiers, lbldob, lblemailaddresses, lblfaxnumber, lblfullfacephoto, lblgeographicdata, lblhealthplanbeneficiarynumber, lblip, lbllinkedin, lblmediarecordnumber, lblname, lblssn, lbltelephonenumber, lbluniqueidentifyingnumber, lblvehicleidentifiers});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgeographicdata)
                    .addComponent(txtgeographicdata, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldob)
                    .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltelephonenumber)
                    .addComponent(txttelephonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfaxnumber)
                    .addComponent(txtfaxnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblemailaddresses)
                    .addComponent(txtemailaddresses, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblssn)
                    .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmediarecordnumber)
                    .addComponent(txtmediarecordnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthealthplanbeneficiarynumber, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblhealthplanbeneficiarynumber, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbankaccountnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbankaccountnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcertificatelicensenumber)
                    .addComponent(txtcertificatelicensenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblvehicleidentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvehicleidentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldeviceidentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdeviceidentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbllinkedin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtip, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbiometricidentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbiometricidentifiers))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfullfacephoto, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfullfacephoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluniqueidentifyingnumber)
                    .addComponent(txtuniqueidentificationnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtName, txtbankaccountnumber, txtbiometricidentifiers, txtcertificatelicensenumber, txtdeviceidentifiers, txtdob, txtemailaddresses, txtfaxnumber, txtfullfacephoto, txtgeographicdata, txthealthplanbeneficiarynumber, txtip, txtlinkedin, txtmediarecordnumber, txtssn, txttelephonenumber, txtuniqueidentificationnumber, txtvehicleidentifier});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblbiometricidentifiers, lblcertificatelicensenumber, lbldeviceidentifiers, lbldob, lblemailaddresses, lblfaxnumber, lblfullfacephoto, lblgeographicdata, lblip, lbllinkedin, lblmediarecordnumber, lblname, lblssn, lbltelephonenumber, lbluniqueidentifyingnumber, lblvehicleidentifiers});

    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtgeographicdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgeographicdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgeographicdataActionPerformed

    private void txtdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdobActionPerformed

    private void txttelephonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelephonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelephonenumberActionPerformed

    private void txtfaxnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfaxnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfaxnumberActionPerformed

    private void txtemailaddressesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailaddressesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailaddressesActionPerformed

    private void txtssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtssnActionPerformed

    private void txtmediarecordnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmediarecordnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmediarecordnumberActionPerformed

    private void txthealthplanbeneficiarynumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthealthplanbeneficiarynumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthealthplanbeneficiarynumberActionPerformed

    private void txtbankaccountnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbankaccountnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbankaccountnumberActionPerformed

    private void txtcertificatelicensenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcertificatelicensenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcertificatelicensenumberActionPerformed

    private void txtvehicleidentifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvehicleidentifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvehicleidentifierActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        product.setName(txtName.getText());
        product.setGeographicdata(txtgeographicdata.getText());
        product.setDateofbirth(txtdob.getText());
        product.setTelephonenumber(txttelephonenumber.getText());
        product.setFaxnumber(txtfaxnumber.getText());
        product.setEmailaddresses(txtemailaddresses.getText());
        product.setSocialsecuritynumber(txtssn.getText());
        product.setMediarecordnumber(txtmediarecordnumber.getText());
        product.setHealthplanbeneficiarynumber(txthealthplanbeneficiarynumber.getText());
        product.setBankaccountnumber(txtbankaccountnumber.getText());
        product.setCertificatelicensenumber(txtcertificatelicensenumber.getText());
        product.setVehicleidentifier(txtvehicleidentifier.getText());
        product.setDeviceidentifier(txtdeviceidentifiers.getText());
        product.setLinkedin(txtlinkedin.getText());
        product.setInternetprotocoladdress(txtip.getText());
        product.setBiometricidentifier(txtbiometricidentifiers.getText());
        product.setFullfacephoto(txtfullfacephoto.getText());
        product.setUniqueidentifier(txtuniqueidentificationnumber.getText());
        JOptionPane.showMessageDialog(this, "Product Information Saved");
     
        
        
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblbankaccountnumber;
    private javax.swing.JLabel lblbiometricidentifiers;
    private javax.swing.JLabel lblcertificatelicensenumber;
    private javax.swing.JLabel lbldeviceidentifiers;
    private javax.swing.JLabel lbldob;
    private javax.swing.JLabel lblemailaddresses;
    private javax.swing.JLabel lblfaxnumber;
    private javax.swing.JLabel lblfullfacephoto;
    private javax.swing.JLabel lblgeographicdata;
    private javax.swing.JLabel lblhealthplanbeneficiarynumber;
    private javax.swing.JLabel lblip;
    private javax.swing.JLabel lbllinkedin;
    private javax.swing.JLabel lblmediarecordnumber;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblssn;
    private javax.swing.JLabel lbltelephonenumber;
    private javax.swing.JLabel lbluniqueidentifyingnumber;
    private javax.swing.JLabel lblvehicleidentifiers;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtbankaccountnumber;
    private javax.swing.JTextField txtbiometricidentifiers;
    private javax.swing.JTextField txtcertificatelicensenumber;
    private javax.swing.JTextField txtdeviceidentifiers;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtemailaddresses;
    private javax.swing.JTextField txtfaxnumber;
    private javax.swing.JTextField txtfullfacephoto;
    private javax.swing.JTextField txtgeographicdata;
    private javax.swing.JTextField txthealthplanbeneficiarynumber;
    private javax.swing.JTextField txtip;
    private javax.swing.JTextField txtlinkedin;
    private javax.swing.JTextField txtmediarecordnumber;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txttelephonenumber;
    private javax.swing.JTextField txtuniqueidentificationnumber;
    private javax.swing.JTextField txtvehicleidentifier;
    // End of variables declaration//GEN-END:variables
}
