/*
 * AdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */

package ui.AdministrativeRole;

import business.Business;
import business.Enterprize.AdminEnterprize;


import business.Enterprize.Enterprize;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;



/**
 *
 * @author  Manisha Bagora
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Business business;
    private UserAccount userAccount;
    private AdminEnterprize enterprize;
    

    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        this.enterprize = (AdminEnterprize) enterprize;

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmanageorganizationuser = new javax.swing.JButton();
        manageEmployeeJButton = new javax.swing.JButton();
        manageOrganizationJButton = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        manageEmployeeJButton1 = new javax.swing.JButton();
        manageOrganizationJButton1 = new javax.swing.JButton();
        btnmanageorganizationuser1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmanageorganizationuser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnmanageorganizationuser.setText("Manage Organization Users");
        btnmanageorganizationuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanageorganizationuserActionPerformed(evt);
            }
        });
        add(btnmanageorganizationuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 295, 30));

        manageEmployeeJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageEmployeeJButton.setText("Manage Organization Employees");
        manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButtonActionPerformed(evt);
            }
        });
        add(manageEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 307, -1, 30));

        manageOrganizationJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageOrganizationJButton.setText("Manage Organizations");
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });
        add(manageOrganizationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 295, 30));

        lblTitle.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        lblTitle.setText("Administrative Work Area");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 479, -1));

        manageEmployeeJButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageEmployeeJButton1.setText("Manage Enterprise Employees");
        manageEmployeeJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButton1ActionPerformed(evt);
            }
        });
        add(manageEmployeeJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 295, 30));

        manageOrganizationJButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageOrganizationJButton1.setText("Manage Enterprize");
        manageOrganizationJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButton1ActionPerformed(evt);
            }
        });
        add(manageOrganizationJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 295, 30));

        btnmanageorganizationuser1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnmanageorganizationuser1.setText("Manage Enterprize Users");
        btnmanageorganizationuser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanageorganizationuser1ActionPerformed(evt);
            }
        });
        add(btnmanageorganizationuser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 295, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adam-niescioruk-hWzrJsS8gwI-unsplash.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-560, -270, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnmanageorganizationuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanageorganizationuserActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, business);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnmanageorganizationuserActionPerformed

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed

        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, business.getOrganizationDirectory());
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed

        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, business.getOrganizationDirectory());
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void manageEmployeeJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButton1ActionPerformed
         ManageEmployeeJPanel2 manageEmployeeJPanel2 = new ManageEmployeeJPanel2(userProcessContainer, business.getenterprizeDirectory());
        userProcessContainer.add("manageEmployeeJPanel2", manageEmployeeJPanel2);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageEmployeeJButton1ActionPerformed

    private void manageOrganizationJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButton1ActionPerformed
       ManageEnterprizeJPanel1 manageEnterprizeJPanel1 = new ManageEnterprizeJPanel1(userProcessContainer, business.getenterprizeDirectory());
        userProcessContainer.add("manageEnterprizeJPanel1", manageEnterprizeJPanel1);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationJButton1ActionPerformed

    private void btnmanageorganizationuser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanageorganizationuser1ActionPerformed
        ManageEnterprizeUserAccountJPanel1 muajp = new ManageEnterprizeUserAccountJPanel1(userProcessContainer, business);
        userProcessContainer.add("ManageEnterprizeUserAccountJPanel1", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnmanageorganizationuser1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmanageorganizationuser;
    private javax.swing.JButton btnmanageorganizationuser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton manageEmployeeJButton;
    private javax.swing.JButton manageEmployeeJButton1;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JButton manageOrganizationJButton1;
    // End of variables declaration//GEN-END:variables
    
}
