/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.AdministrativeRole;

import business.Enterprize.Enterprize;
import business.Enterprize.Enterprize.Type;
import business.Enterprize.EnterprizeDirectory;

import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manisha Bagora
 */
public class ManageEnterprizeJPanel1 extends javax.swing.JPanel {

    private EnterprizeDirectory directory;
    private JPanel userProcessContainer;
    
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageEnterprizeJPanel1(JPanel userProcessContainer,EnterprizeDirectory directory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.directory = directory;
        
        populateTable1();
        populateCombo();
    }
    
    @SuppressWarnings("unchecked")
    private void populateCombo(){
        cmbEnterprize.removeAllItems();
        for (Type type : Enterprize.Type.values()){
            if (!type.getValue().equals(Type.AdminE.getValue()))
                cmbEnterprize.addItem(type);
        }
    }

    private void populateTable1(){
        DefaultTableModel model = (DefaultTableModel) tblEnterprize.getModel();
        
        model.setRowCount(0);
        
        for (Enterprize enterprize : directory.getenterprizeList()){
            Object[] row = new Object[2];
            row[0] = enterprize.getEnterprizeID();
            row[1] = enterprize.getName();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnterprize = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        cmbEnterprize = new javax.swing.JComboBox();
        lblSelectOrgType = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblOrganizationList = new javax.swing.JLabel();
        lblOrganizationAdd = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEnterprize.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEnterprize);
        if (tblEnterprize.getColumnModel().getColumnCount() > 0) {
            tblEnterprize.getColumnModel().getColumn(0).setResizable(false);
            tblEnterprize.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 480, 92));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 87, -1));

        cmbEnterprize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbEnterprize, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 167, -1));

        lblSelectOrgType.setText("Select Enterprize Type:");
        add(lblSelectOrgType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblTitle.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        lblTitle.setText("Manage Enterprize");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 460, -1));

        lblOrganizationList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblOrganizationList.setText("Enterprize List:");
        add(lblOrganizationList, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        lblOrganizationAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblOrganizationAdd.setText("Add Enterprize:");
        add(lblOrganizationAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/organization.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        Type type = (Type) cmbEnterprize.getSelectedItem();
        directory.createEnterprize(type);
        populateTable1();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox cmbEnterprize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOrganizationAdd;
    private javax.swing.JLabel lblOrganizationList;
    private javax.swing.JLabel lblSelectOrgType;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblEnterprize;
    // End of variables declaration//GEN-END:variables
}
